/**
 * Ländercodes je deutschem Team-Namen (wie in lib/teams.ts ausgegeben).
 *
 * Wir nutzen bewusst KEINE Flaggen-Emojis: Windows/Chrome zeigt die nämlich
 * nur als zwei Buchstaben ("DE") statt als Flagge. Stattdessen liefern wir
 * ISO-Codes, aus denen die <Flag>-Komponente ein echtes SVG-Bild lädt.
 */
const CODES: Record<string, string> = {
  Deutschland: "de",
  Curaçao: "cw",
  Elfenbeinküste: "ci",
  Ecuador: "ec",
  Schweden: "se",
  Tunesien: "tn",
  Spanien: "es",
  "Kap Verde": "cv",
  Belgien: "be",
  Ägypten: "eg",
  Iran: "ir",
  Neuseeland: "nz",
  Frankreich: "fr",
  Senegal: "sn",
  Irak: "iq",
  Norwegen: "no",
  Argentinien: "ar",
  Algerien: "dz",
  Österreich: "at",
  Jordanien: "jo",
  Portugal: "pt",
  "DR Kongo": "cd",
  England: "gb-eng",
  Kroatien: "hr",
  Ghana: "gh",
  Panama: "pa",
  Usbekistan: "uz",
  Kolumbien: "co",
  Brasilien: "br",
  Niederlande: "nl",
  USA: "us",
  Mexiko: "mx",
  Kanada: "ca",
  Japan: "jp",
  Südkorea: "kr",
  Australien: "au",
  Marokko: "ma",
  Schweiz: "ch",
  Dänemark: "dk",
  Italien: "it",
  Polen: "pl",
  Schottland: "gb-sct",
  Wales: "gb-wls",
  "Saudi-Arabien": "sa",
  Uruguay: "uy",
  Katar: "qa",
  Südafrika: "za",
  Nigeria: "ng",
  Kamerun: "cm",
  Paraguay: "py",
  Peru: "pe",
  Chile: "cl",
  Türkei: "tr",
  Griechenland: "gr",
  Serbien: "rs",
  Ukraine: "ua",
  Tschechien: "cz",
  Ungarn: "hu",
  Rumänien: "ro",
  Haiti: "ht",
  Jamaika: "jm",
  Neukaledonien: "nc",
};

/** ISO-/Regionscode für ein Team (z.B. "de", "gb-eng") oder null. */
export function teamFlagCode(name: string): string | null {
  return CODES[name] ?? null;
}
