/**
 * Flaggen-Emojis je deutschem Team-Namen (wie in lib/teams.ts ausgegeben).
 * Wird rein dekorativ in der UI genutzt – fehlt ein Eintrag, gibt es ⚽ zurück.
 */
const FLAGS: Record<string, string> = {
  Deutschland: "🇩🇪",
  Curaçao: "🇨🇼",
  Elfenbeinküste: "🇨🇮",
  Ecuador: "🇪🇨",
  Schweden: "🇸🇪",
  Tunesien: "🇹🇳",
  Spanien: "🇪🇸",
  "Kap Verde": "🇨🇻",
  Belgien: "🇧🇪",
  Ägypten: "🇪🇬",
  Iran: "🇮🇷",
  Neuseeland: "🇳🇿",
  Frankreich: "🇫🇷",
  Senegal: "🇸🇳",
  Irak: "🇮🇶",
  Norwegen: "🇳🇴",
  Argentinien: "🇦🇷",
  Algerien: "🇩🇿",
  Österreich: "🇦🇹",
  Jordanien: "🇯🇴",
  Portugal: "🇵🇹",
  "DR Kongo": "🇨🇩",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Kroatien: "🇭🇷",
  Ghana: "🇬🇭",
  Panama: "🇵🇦",
  Usbekistan: "🇺🇿",
  Kolumbien: "🇨🇴",
  Brasilien: "🇧🇷",
  Niederlande: "🇳🇱",
  USA: "🇺🇸",
  Mexiko: "🇲🇽",
  Kanada: "🇨🇦",
  Japan: "🇯🇵",
  Südkorea: "🇰🇷",
  Australien: "🇦🇺",
  Marokko: "🇲🇦",
  Schweiz: "🇨🇭",
  Dänemark: "🇩🇰",
  Italien: "🇮🇹",
  Polen: "🇵🇱",
  Schottland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Saudi-Arabien": "🇸🇦",
  Uruguay: "🇺🇾",
  Katar: "🇶🇦",
  Südafrika: "🇿🇦",
  Nigeria: "🇳🇬",
  Kamerun: "🇨🇲",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Chile: "🇨🇱",
  Türkei: "🇹🇷",
  Griechenland: "🇬🇷",
  Serbien: "🇷🇸",
  Ukraine: "🇺🇦",
  Tschechien: "🇨🇿",
  Ungarn: "🇭🇺",
  Rumänien: "🇷🇴",
  Haiti: "🇭🇹",
  Jamaika: "🇯🇲",
  Neukaledonien: "🇳🇨",
};

/** Flaggen-Emoji für ein Team (Fallback: ⚽). */
export function teamFlag(name: string): string {
  return FLAGS[name] ?? "⚽";
}
